categories:
    type:     rest
    resource: AppBundle\Controller\CategoriesController

config:
    type:     rest
    resource: AppBundle\Controller\ConfigController

markers:
    type:     rest
    resource: AppBundle\Controller\MarkersController

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
