categories:
    type:     rest
    resource: AppBundle\Controller\CategoriesController

config:
    type:     rest
    resource: AppBundle\Controller\ConfigController

markers:
    type:     rest
    resource: AppBundle\Controller\MarkersController